#配置端口
server:
  port: 8080
spring:
  datasource:
    #数据源
    druid:
      url: jdbc:mysql://39.99.145.48:3306/repository_erp?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123525lbl.
      max-active: 20
      initial-size: 5
      min-idle: 5
      max-idle: 10
      validation-query: select 1
      stat-view:
        login-username: admin
        login-password: admin
        allow:
        deny:
        url-mapping:
          - "/druid/*"
      type: com.alibaba.druid.pool.DruidDataSource

